# Mia Katz, 9/8/18
# This is a Mad Libs game. You'll enter nouns, adjectives, and more to put together something fun at the end!
# By fun, I mean the lyrics to Africa, by Toto
# The most challenging part was configuring the collection of inputs at the bottom, and formatting them properly
# I used an article from pythonforbeginners.com to help me figure out how to put these comments in. Toto should be credited for their lyrics as well. 
print('Welcome to Mad Libs! Please name a noun')
noun1 = input()
print('Name a verb ending in ing')
ing = input()
print('Name a plural noun ')
noun2 = input()
print('Name an adjective ')
ad = input()
print('Name another verb ending in ing ')
ing2 = input()
print('Name a time of day')
time = input()
print('Another adjective')
ad2 = input()
print('A verb, please')
verb = input()
print('Time to choose a plural noun!')
noun3 = input()
print('Name a verb ending in ed')
ed = input()
print('An adjective')
ad3 = input()
print('A person. Any person')
person = input()
print('Now, a verb')
verb2 = input()
print('Adjective')
ad4 = input()
print('Another adjective. Do not repeat')
ad5 = input()
print('A new plural noun!')
plu = input()
print('Pronoun of that person from earlier (he, she, they, etc)')
pro = input()
print('The most exciting verb you can think of, past tense')
verb3 = input()
print('A new verb')
verb4 = input()
print('A verb, but it ends with ing')
ing4 = input()
print('A ridiculous noun')
fun = input()
print('Something you care about deeply')
an = input()
print('A large number')
num = input()
print('A strong, plural noun')
big = input()
print('A better plural noun')
rains = input()
print('Any place you can think of')
place = input()
print('A meaningful noun')
nn = input()
print('Last one, a fun verb')
final = input()
print('Africa, by Toto')
print('I hear the ' +noun1+ ' ' +ing+ ' tonight.')
print('But she hears only '+noun2+ ' of some '+ad+ ' conversation.')
print('She is '+ing2+ ' in, '+time+ ' flight.')
print('The '+ad2+ ' wings '+verb+ ' the '+noun3+' that guide me towards salvation.')
print('I '+ed+ 'a(n) '+ad3+ ' ' +person+ ' along the way.')
print('Hoping to find some long '+ad4+ ' ' +ad5+ ' or ancient ' +plu+' ' )
print(' '+pro+ ' ' +verb3+ ' to me as if to ' +verb4+ ', Hurry boy, it is ' +ing4+ ' there for you')
print('It is gonna take a '+fun+ 'to take me away from ' +an+ ' ')
print('There is nothing that a ' +num+ ' ' +big+ ' or more could ever do.')
print('I bless the '+rains+ ' down in ' +place+ ' ')
print('Gonna take some ' +nn+' to '+final+ ' the things we never had.')

